
# Title - nextcloud-wip
# Description - ...
# Note - 

version: '2'

services:
  db:
    container_name: nextclouddb
    image: mariadb:10.6
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /data/nextcloud/db:/var/lib/mysql
    networks:
      - myNetwork      #DD- This network was created manually using Portainer
    environment:
      - MYSQL_ROOT_PASSWORD=CHANGE-ME
      - MYSQL_PASSWORD=CHANGE-ME
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    container_name: nextcloudapp
    image: nextcloud
    restart: unless-stopped
    ports:
      - 8085:80
    links:
      - db
    volumes:
      - /data/nextcloud/app:/var/www/html
    networks:
      - myNetwork      #DD- This network was created manually using Portainer
    environment:
      - MYSQL_PASSWORD=CHANGE-ME
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db

networks:
  myNetwork:           #DD- This network was created manually using Portainer
    external: true
